"""Add sync flag and timezone support

Revision ID: 0c75f87697f2
Revises: 73319d813f55
Create Date: 2025-08-08 09:26:51.388245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c75f87697f2'
down_revision = '73319d813f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_syncing_history', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.drop_column('is_syncing_history')

    # ### end Alembic commands ###
