"""Make store timestamp timezone aware

Revision ID: 58d6af1dd02f
Revises: 75d02c0ccf29
Create Date: 2025-08-06 14:07:20.182426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58d6af1dd02f'
down_revision = '75d02c0ccf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.alter_column('last_notified_order_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.alter_column('last_notified_order_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
