"""Add note column to woocommerce_order table

Revision ID: 65b0c6701019
Revises: 58d6af1dd02f
Create Date: 2025-08-06 21:58:02.528978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b0c6701019'
down_revision = '58d6af1dd02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
