"""Add wc_line_item_id to OrderLineItem

Revision ID: 75d02c0ccf29
Revises: d4ea3df96fb2
Create Date: 2025-08-06 12:29:24.400424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d02c0ccf29'
down_revision = 'd4ea3df96fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wc_line_item_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_order_line_item_wc_line_item_id'), ['wc_line_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_line_item_wc_line_item_id'))
        batch_op.drop_column('wc_line_item_id')

    # ### end Alembic commands ###
