"""Add image_url to line items

Revision ID: 779f7021bae3
Revises: ad7f3637918a
Create Date: 2025-08-06 01:58:44.043845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779f7021bae3'
down_revision = 'ad7f3637918a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
