"""Add FulfillmentSetting model

Revision ID: 979628a3c1f8
Revises: e299a1fcba23
Create Date: 2025-08-07 23:34:02.113901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979628a3c1f8'
down_revision = 'e299a1fcba23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_name', name='_user_provider_uc')
    )
    with op.batch_alter_table('fulfillment_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fulfillment_setting_provider_name'), ['provider_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fulfillment_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fulfillment_setting_provider_name'))

    op.drop_table('fulfillment_setting')
    # ### end Alembic commands ###
