"""Add variation columns to line items

Revision ID: ad7f3637918a
Revises: f6810444a7eb
Create Date: 2025-08-06 00:53:12.091121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7f3637918a'
down_revision = 'f6810444a7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('var1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('var2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('var3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('var4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('var5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('var6', sa.String(length=255), nullable=True))
        batch_op.drop_column('variations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variations', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.drop_column('var6')
        batch_op.drop_column('var5')
        batch_op.drop_column('var4')
        batch_op.drop_column('var3')
        batch_op.drop_column('var2')
        batch_op.drop_column('var1')

    # ### end Alembic commands ###
