"""Add timezone to WooCommerceStore last_checked

Revision ID: b72789c8cb49
Revises: bbd1c9702621
Create Date: 2025-08-07 13:51:20.425868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b72789c8cb49'
down_revision = 'bbd1c9702621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.alter_column('last_checked',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('last_notified_order_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notified_order_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('last_checked',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
