"""Add order_modified_at column to WooCommerceOrder

Revision ID: bbd1c9702621
Revises: 65b0c6701019
Create Date: 2025-08-07 13:37:46.331868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd1c9702621'
down_revision = '65b0c6701019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_modified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_woocommerce_order_order_modified_at'), ['order_modified_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_woocommerce_order_order_modified_at'))
        batch_op.drop_column('order_modified_at')

    # ### end Alembic commands ###
