"""Initial migration.

Revision ID: c98aaa891d52
Revises: 
Create Date: 2025-08-05 21:52:37.606174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98aaa891d52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_add_store', sa.Boolean(), nullable=False),
    sa.Column('can_delete_store', sa.Boolean(), nullable=False),
    sa.Column('can_edit_store', sa.Boolean(), nullable=False),
    sa.Column('can_view_orders', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_send_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('can_customize_telegram_templates', sa.Boolean(), nullable=False),
    sa.Column('can_customize_telegram_delay', sa.Boolean(), nullable=False),
    sa.Column('telegram_template_new_order', sa.Text(), nullable=True),
    sa.Column('telegram_template_user_test', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_username'), ['username'], unique=True)

    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('background_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('requested_cancellation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_task_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_background_task_status'), ['status'], unique=False)

    op.create_table('woocommerce_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('store_url', sa.String(length=255), nullable=False),
    sa.Column('consumer_key', sa.String(length=255), nullable=False),
    sa.Column('consumer_secret', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_notified_order_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_url')
    )
    op.create_table('woocommerce_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wc_order_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('payment_method_title', sa.String(length=100), nullable=True),
    sa.Column('products_json', sa.Text(), nullable=True),
    sa.Column('order_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['woocommerce_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wc_order_id', 'store_id', name='_wc_order_store_uc')
    )
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_woocommerce_order_order_created_at'), ['order_created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_woocommerce_order_wc_order_id'), ['wc_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_woocommerce_order_wc_order_id'))
        batch_op.drop_index(batch_op.f('ix_woocommerce_order_order_created_at'))

    op.drop_table('woocommerce_order')
    op.drop_table('woocommerce_store')
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_task_status'))
        batch_op.drop_index(batch_op.f('ix_background_task_job_id'))

    op.drop_table('background_task')
    op.drop_table('setting')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_username'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
