"""Refactor OrderLineItem variations

Revision ID: d4ea3df96fb2
Revises: d5743442dceb
Create Date: 2025-08-06 11:32:59.350175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ea3df96fb2'
down_revision = 'd5743442dceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variations', sa.Text(), nullable=True))
        batch_op.drop_column('var6')
        batch_op.drop_column('var2')
        batch_op.drop_column('var1')
        batch_op.drop_column('var3')
        batch_op.drop_column('var4')
        batch_op.drop_column('var5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('var5', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var4', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var6', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('variations')

    # ### end Alembic commands ###
