"""Add OrderLineItem table and full order details

Revision ID: f6810444a7eb
Revises: c98aaa891d52
Create Date: 2025-08-06 00:26:30.903424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6810444a7eb'
down_revision = 'c98aaa891d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('variations', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['woocommerce_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=500), nullable=True))
        batch_op.drop_column('products_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('billing_email')
        batch_op.drop_column('billing_phone')
        batch_op.drop_column('customer_note')
        batch_op.drop_column('shipping_total')

    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    op.drop_table('order_line_item')
    # ### end Alembic commands ###
