"""Add image_url to line items

Revision ID: f8f34ea79706
Revises: 779f7021bae3
Create Date: 2025-08-06 03:03:24.262659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f34ea79706'
down_revision = '779f7021bae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
